### ISSUE TITLE
Failed to launch JVM

### ISSUE THREAD

**Issue by Vicent9920** [fengzhizi715/Monica#4]
指定`JDK`为`17`，`JAVA-HOME`也配置的`17`，但是打包后运行依然报错：`Failed to launch JVM`
已自行通过`ChatGPT`尝试解决无果，切换`packageExe`和`packageMsi`还是无果。

**Comment by fengzhizi715** [comment]
windows 系统吗？我在 windows 上试过可以用 packageExe ，可能是少了3个模型的缘故。(我一直没传上去，因为太大了，如果需要的话可以联系一下我，我发你邮箱)

**Comment by Vicent9920** [comment]
已发送邮件，大佬请查看邮箱，谢谢！
